---
name: Build container images

on:
  push:
    branches: [ $default-branch, imagefactory ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  Run-ImageFactory-Builds:
    runs-on: self-hosted
    steps:
      - name: Checkout sig-cloud-instance-images
        uses: actions/checkout@v2

      - name: Build images
        run: make

