---
name: Build container images

on:
  push:
    branches: [ $default-branch, imagefactory ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  Run-ImageFactory-Builds:
    strategy:
      matrix: 
        architecture:
          - x64
          - ARM64
    runs-on: 
      - self-hosted
      - ${{ matrix.architecture }}
    steps:
      - name: Checkout sig-cloud-instance-images
        uses: actions/checkout@v2

      - name: Build images
        run: make
    
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: rocky-${{ matrix.architecture }}.tar.xz
          path: *.tar.xz
        if-no-files-found: error
