---
name: Build container images

on:
  push:
    branches: [ $default-branch, imagefactory ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  Run-ImageFactory-Builds:
    strategy:
      matrix: 
        arch: [ x64, ARM64 ]
    runs-on: [ self-hosted, ${{ matrix.arch }} ]
    steps:
      - name: Checkout sig-cloud-instance-images
        uses: actions/checkout@v2

      - name: Build images
        run: make

